○の記号で表示されている場合は、要素ごとに丸の中にある記号の処理を行っていく。
⊕　→　要素ごとに足し算を行う。<br>
⊗　→　要素ごとに掛け算を行っている。<br>

例
[2.0 , 1.0] ⊕　[x1 , x2] →　[x1 + 2.0 , x2 + 1.0]

[x1 + 2.0 , x2 + 1.0] ⊗　[3.0 , 4.0] → [3.0(x1 + 2.0 ), 4.0(x2 + 1.0)]<br>
 [3.0(x1 + 2.0 ), 4.0(x2 + 1.0)] ⇒　tanh →　 [tanh(3.0(x1 + 2.0 )), tanh(4.0(x2 + 1.0))]

□の記号で表されているのはNNの層<br>
重みづけが入るところが異なってくる。<br>
x →　σ　⇒σ(Wx + b) <br>
W:重み 　　b:バイアス　　を表している。

identity→恒等式という意味でそのままの値を渡している。

dim = 1→チャネル方向に積み上げていく

In [1]:
import torch
a = torch.randn(1,4)
print(a)

tensor([[-0.6398, -0.1958,  0.0625,  1.7903]])


In [2]:
torch.argmax(a , dim = 1)

tensor([3])

In [3]:
b = torch.randn(4,4)
print(b)

tensor([[ 0.0548, -0.4078,  0.4590,  0.8414],
        [-0.5523,  0.3284,  0.0148, -0.9540],
        [ 0.1210,  0.9880,  0.0320,  0.6532],
        [-0.2381,  1.6864, -0.7544,  0.3769]])


In [4]:
torch.argmax(b , dim = 1)

tensor([3, 1, 1, 1])

In [5]:
torch.argmax(b , dim = 0)

tensor([2, 3, 0, 0])